name: export-and-branch-solution-import-to-test
# This Action:
# Exports Power Apps $DEFAULTSOLUTIOfrom $DEVENVURL dataverse dev environment
# Create a development branch based on Main
# Checks unpacked solution in to dev branch
# rebuilds on $BUILD_ENVIRONMENT_URL build envirnment serer
# imports managed $DEFAULTSOLUTION to $TEST_ENVIRONMETN_URL dataverse test environment
# Create a pull request on the Development branch to check back into MAIN
# to push to $PRODUCTION_ENVIRONMENT_URL,  Create a new Release, which will kick off the Release-Action
#
# Instructions:   (https://learn.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-start)
# Create Required Dev,Test,Build,Prod environments    (https://learn.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-start#create-required-environments)

on:
  workflow_dispatch:
    inputs:

      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/
  
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{vars.DEVENVURL}}
        app-id: ${{vars.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{vars.TENANT_ID}}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{vars.DEVENVURL}}
        app-id: ${{vars.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{vars.TENANT_ID}}
        solution-name: ${{vars.DEFAULTSOLUTION}}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ vars.DEFAULTSOLUTION }}.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ vars.DEFAULTSOLUTION }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ vars.DEFAULTSOLUTION }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ vars.DEFAULTSOLUTION }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ vars.DEFAULTSOLUTION }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true

  Import-to-test:
    needs: [ export-from-dev ]
    uses: ./.github/workflows/import-to-test.yml     
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
      
